### ISSUE TITLE
`wordValue` vs `wordValuePrese`

### ISSUE THREAD

**Issue by jtagcat** [keeleinstituut/ekilex#37]
```
            "wordId": 237885,
            "wordValue": "suuline",
            "wordValuePrese": "suuline",
```

Mis vahe on kahel väärtusel; mida peaks `Prese` märkima?

**Comment by indrekhein** [comment]
Prese on "esitluskuju" ja võib sisaldada <eki-...> märgendust. Formatiiv (laias laastus käändelõpp) on roheliseks värvitud, tsitaatsõnad kursiivis, vene keele rohulised vokaalid poolpaksud, B12-vitamiin on alaindeksiga jne. Prese on ka muudel tekstielementidel, seal on muidki kasutusviise.
Value ei sisalda märgendust ja on sobiv programmidele otsimiseks, järjestamiseks jne.
